Feature/testing api ocr
Lambda-School-Labs/human-rights-first-docdb-ds pull request #4
Opened 2021-10-15 20:12 UTC by joshua-araujo

## Description
Created script to test functions of Box API to retrieve information from folders and download files.  Once files are downloaded we run OCR on them.  Dependencies required for this change is boxsdk.

Please delete options that are not relevant.
- [x] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Test A
- [ ] Test B

**Test Configuration**:
* SDK: boxsdk

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] I have checked my code and corrected any misspellings

2021-10-15 20:15 UTC, pflee1989 approved these changes

2021-10-15 20:15 UTC, pflee1989 commented on app/testing.py
> +import pytesseract
Great work, let's build this out to automate more retrieval transactions.

2021-10-17 07:58 UTC, andrewsbusby approved these changes
Looks good to me as far as I can tell.

2021-10-17 23:53 UTC, paulstgermain requested changes
This is looking pretty good, but I'd like for you to include the standard Loom recording explaining this PR and showcasing the changes you made - requesting changes until that recording is included!

2021-10-19 01:44 UTC, tinomen commented on app/testing.py
> +me = client.user().get()
Why are we setting this unused variable?

2021-10-27 20:35 UTC, closed without merging